pub mod activation;
pub mod builtin;
pub mod context;
pub mod crypto;
pub mod executor;
pub mod expression;
pub mod import;
pub mod persistence;
pub mod runner;
pub mod runner_helpers;
pub mod runners_ai;
pub mod runners_code;
pub mod runners_db;
pub mod runners_email;
pub mod runners_filesystem;
pub mod runners_iteration;
pub mod runners_social;
pub mod runners_switch_batches;
pub mod runners_triggers;
pub mod scheduler;
pub mod stub_runners;
pub mod subflow;
pub mod templates_library;
pub mod types;

pub use activation::{ActivationState, load_activation_state, save_activation_state, set_flow_active};
pub use builtin::{HttpRequestRunner, SlackPostRunner, register_builtin_runners};
pub use context::ExecutionContext;
pub use executor::{execute_flow, execute_single_node};
pub use expression::{ExpressionContext, ExpressionError, evaluate_expression, evaluate_template, resolve_field, resolve_string};
pub use import::{N8nWorkflow, import_n8n_json};
pub use persistence::{FlowRunPersistence, RunRecord, RunSummary};
pub use runner::{NodeRunContext, NodeRunner, NodeRunnerRegistry};
pub use runner_helpers::{first_input_item, make_expr_ctx, merged_inputs, properties_lookup};
pub use runners_ai::{AnthropicRunner, OpenAiRunner, register_ai_runners};
pub use runners_code::{CodeRunner, register_code_runner};
pub use runners_db::{SqliteRunner, register_db_runners};
pub use runners_email::{SmtpRunner, register_email_runners};
pub use runners_filesystem::{FileReadRunner, FileWriteRunner, register_filesystem_runners};
pub use runners_iteration::{SplitOutRunner, register_iteration_runners};
pub use runners_social::{AirtableRunner, DiscordWebhookRunner, GitHubIssueRunner, GoogleSheetsRunner, NotionRunner, TelegramRunner, register_social_runners};
pub use runners_switch_batches::{SplitInBatchesRunner, SwitchRunner, register_switch_and_batches};
pub use runners_triggers::{CronTriggerRunner, ManualTriggerRunner, WebhookTriggerRunner, register_trigger_runners};
pub use scheduler::{FlowActivation, FlowScheduler, build_and_start_scheduler};
pub use stub_runners::{PassthroughRunner, register_passthrough_runners};
pub use subflow::{SubWorkflowRunner, register_sub_workflow_runner};
pub use templates_library::{TemplateSummary, built_in_templates, export_flow_json, materialize_template};
pub use types::{BinaryData, FlowExecutionReport, NodeExecutionData, NodeExecutionError, NodeExecutionRecord, NodeExecutionStatus, NodeItem, NodeRunOutcome};

pub fn default_registry() -> NodeRunnerRegistry {
  let mut registry = NodeRunnerRegistry::new();
  register_passthrough_runners(&mut registry);
  register_builtin_runners(&mut registry);
  register_switch_and_batches(&mut registry);
  register_code_runner(&mut registry);
  register_trigger_runners(&mut registry);
  register_ai_runners(&mut registry);
  register_filesystem_runners(&mut registry);
  register_social_runners(&mut registry);
  register_email_runners(&mut registry);
  register_db_runners(&mut registry);
  register_iteration_runners(&mut registry);
  registry
}
