use serde_json::json;

use lx_graph_editor::catalog::{GraphFieldKind, GraphFieldOption, GraphFieldSchema, GraphNodeTemplate, GraphPortTemplate, PortDirection};

pub fn workflow_node_templates() -> Vec<GraphNodeTemplate> {
  vec![
    GraphNodeTemplate {
      id: "topic_input".to_string(),
      label: "Topic Input".to_string(),
      description: Some("Seeds the workflow with monitored themes.".to_string()),
      category: Some("inputs".to_string()),
      default_label: Some("Topics".to_string()),
      ports: vec![GraphPortTemplate {
        id: "topics".to_string(),
        label: "Topics".to_string(),
        description: Some("Topics to monitor".to_string()),
        direction: PortDirection::Output,
        data_type: Some("topics".to_string()),
        required: true,
        allow_multiple: true,
      }],
      fields: vec![
        GraphFieldSchema {
          id: "topics".to_string(),
          label: "Topics".to_string(),
          description: Some("Theme list for the aggregation pass".to_string()),
          kind: GraphFieldKind::StringList,
          required: true,
          default_value: Some(json!(["AI policy", "chip supply chain", "open models"])),
        },
        GraphFieldSchema {
          id: "refresh_window_hours".to_string(),
          label: "Refresh Window".to_string(),
          description: Some("How far back the fetch step should look".to_string()),
          kind: GraphFieldKind::Integer,
          required: true,
          default_value: Some(json!(12)),
        },
      ],
    },
    GraphNodeTemplate {
      id: "curated_sources".to_string(),
      label: "Curated Sources".to_string(),
      description: Some("Source domains and feeds to prioritize".to_string()),
      category: Some("inputs".to_string()),
      default_label: Some("Sources".to_string()),
      ports: vec![GraphPortTemplate {
        id: "sources".to_string(),
        label: "Sources".to_string(),
        description: Some("Preferred source list".to_string()),
        direction: PortDirection::Output,
        data_type: Some("sources".to_string()),
        required: true,
        allow_multiple: true,
      }],
      fields: vec![GraphFieldSchema {
        id: "domains".to_string(),
        label: "Domains".to_string(),
        description: Some("Preferred source domains".to_string()),
        kind: GraphFieldKind::StringList,
        required: true,
        default_value: Some(json!(["www.ft.com", "www.semafor.com", "www.stratechery.com"])),
      }],
    },
    GraphNodeTemplate {
      id: "web_fetch".to_string(),
      label: "Web Fetch".to_string(),
      description: Some("Fetches candidate articles from sources".to_string()),
      category: Some("fetch".to_string()),
      default_label: Some("Fetch".to_string()),
      ports: vec![
        GraphPortTemplate {
          id: "topics".to_string(),
          label: "Topics".to_string(),
          description: None,
          direction: PortDirection::Input,
          data_type: Some("topics".to_string()),
          required: true,
          allow_multiple: false,
        },
        GraphPortTemplate {
          id: "sources".to_string(),
          label: "Sources".to_string(),
          description: None,
          direction: PortDirection::Input,
          data_type: Some("sources".to_string()),
          required: true,
          allow_multiple: false,
        },
        GraphPortTemplate {
          id: "articles".to_string(),
          label: "Articles".to_string(),
          description: None,
          direction: PortDirection::Output,
          data_type: Some("articles".to_string()),
          required: true,
          allow_multiple: true,
        },
      ],
      fields: vec![
        GraphFieldSchema {
          id: "per_source_limit".to_string(),
          label: "Per-source Limit".to_string(),
          description: Some("Maximum articles per source".to_string()),
          kind: GraphFieldKind::Integer,
          required: true,
          default_value: Some(json!(8)),
        },
        GraphFieldSchema {
          id: "follow_redirects".to_string(),
          label: "Follow Redirects".to_string(),
          description: None,
          kind: GraphFieldKind::Boolean,
          required: true,
          default_value: Some(json!(true)),
        },
      ],
    },
    GraphNodeTemplate {
      id: "extract_signals".to_string(),
      label: "Extract Signals".to_string(),
      description: Some("Pulls structured newsworthy signals from raw articles".to_string()),
      category: Some("transform".to_string()),
      default_label: Some("Extract".to_string()),
      ports: vec![
        GraphPortTemplate {
          id: "articles".to_string(),
          label: "Articles".to_string(),
          description: None,
          direction: PortDirection::Input,
          data_type: Some("articles".to_string()),
          required: true,
          allow_multiple: false,
        },
        GraphPortTemplate {
          id: "signals".to_string(),
          label: "Signals".to_string(),
          description: None,
          direction: PortDirection::Output,
          data_type: Some("signals".to_string()),
          required: true,
          allow_multiple: true,
        },
      ],
      fields: vec![GraphFieldSchema {
        id: "focus".to_string(),
        label: "Focus".to_string(),
        description: Some("What to pull out of each document".to_string()),
        kind: GraphFieldKind::TextArea,
        required: true,
        default_value: Some(json!("Major announcements, partnerships, funding, policy shifts, and credible product launches.")),
      }],
    },
    GraphNodeTemplate {
      id: "dedupe_rank".to_string(),
      label: "Dedupe + Rank".to_string(),
      description: Some("Collapses duplicates and scores urgency".to_string()),
      category: Some("transform".to_string()),
      default_label: Some("Score".to_string()),
      ports: vec![
        GraphPortTemplate {
          id: "signals".to_string(),
          label: "Signals".to_string(),
          description: None,
          direction: PortDirection::Input,
          data_type: Some("signals".to_string()),
          required: true,
          allow_multiple: false,
        },
        GraphPortTemplate {
          id: "ranked".to_string(),
          label: "Ranked".to_string(),
          description: None,
          direction: PortDirection::Output,
          data_type: Some("ranked_items".to_string()),
          required: true,
          allow_multiple: true,
        },
      ],
      fields: vec![
        GraphFieldSchema {
          id: "freshness_bias".to_string(),
          label: "Freshness Bias".to_string(),
          description: None,
          kind: GraphFieldKind::Number,
          required: true,
          default_value: Some(json!(0.72)),
        },
        GraphFieldSchema {
          id: "entity_overlap_penalty".to_string(),
          label: "Entity Overlap Penalty".to_string(),
          description: None,
          kind: GraphFieldKind::Number,
          required: true,
          default_value: Some(json!(0.35)),
        },
      ],
    },
    GraphNodeTemplate {
      id: "summarize_briefs".to_string(),
      label: "Summarize Briefs".to_string(),
      description: Some("Produces digest-ready summaries".to_string()),
      category: Some("transform".to_string()),
      default_label: Some("Summarize".to_string()),
      ports: vec![
        GraphPortTemplate {
          id: "ranked".to_string(),
          label: "Ranked".to_string(),
          description: None,
          direction: PortDirection::Input,
          data_type: Some("ranked_items".to_string()),
          required: true,
          allow_multiple: false,
        },
        GraphPortTemplate {
          id: "briefs".to_string(),
          label: "Briefs".to_string(),
          description: None,
          direction: PortDirection::Output,
          data_type: Some("briefs".to_string()),
          required: true,
          allow_multiple: true,
        },
      ],
      fields: vec![GraphFieldSchema {
        id: "style".to_string(),
        label: "Style".to_string(),
        description: None,
        kind: GraphFieldKind::Select {
          options: vec![
            GraphFieldOption { value: "bullet".to_string(), label: "Bullet".to_string() },
            GraphFieldOption { value: "briefing".to_string(), label: "Briefing".to_string() },
          ],
        },
        required: true,
        default_value: Some(json!("briefing")),
      }],
    },
    GraphNodeTemplate {
      id: "feed_output".to_string(),
      label: "Feed Output".to_string(),
      description: Some("Publishes the ranked briefs into the reader feed".to_string()),
      category: Some("output".to_string()),
      default_label: Some("Feed".to_string()),
      ports: vec![GraphPortTemplate {
        id: "briefs".to_string(),
        label: "Briefs".to_string(),
        description: None,
        direction: PortDirection::Input,
        data_type: Some("briefs".to_string()),
        required: true,
        allow_multiple: false,
      }],
      fields: vec![
        GraphFieldSchema {
          id: "channel".to_string(),
          label: "Channel".to_string(),
          description: None,
          kind: GraphFieldKind::Text,
          required: true,
          default_value: Some(json!("daily-intel")),
        },
        GraphFieldSchema {
          id: "max_items".to_string(),
          label: "Max Items".to_string(),
          description: None,
          kind: GraphFieldKind::Integer,
          required: true,
          default_value: Some(json!(12)),
        },
      ],
    },
  ]
}
